### ISSUE TITLE
tv version 

### ISSUE THREAD

**Issue by Gaitin** [yangxiaoge/yangxiaoge.github.io#1]
Tv version, touch screen sliding page, the page will be automatically topped
tv版本 触屏滑动页面 页面会自动置顶

**Comment by yangxiaoge** [comment]
网页只收集，app bug可以到 https://github.com/FongMi 联系作者

**Comment by Gaitin** [comment]
> 网页只收集，app bug可以到 https://github.com/FongMi 联系作者

OK
